version: '3.7'
services:

  php-fpm:
    image: localhost/calculator-php-fpm:latest
    restart: always
    container_name: calculator-php-fpm
    environment:
      X_API_KEY: ${X_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}


    volumes:
      - ./:/var/www/html
    
      

  nginx:
    image: localhost/calculator-nginx:latest
    restart: always
    container_name: calculator-nginx
    ports:
      - ${APP_WEB_PORT}:80
    environment:
      PHP_UPSTREAM_CONTAINER: php-fpm
      PHP_UPSTREAM_PORT: 9000
      APP_WEB_PORT: ${APP_WEB_PORT}
    depends_on:
      - php-fpm
    volumes:
      - ./web:/var/www/html/web

  swagger:
    image: swaggerapi/swagger-ui:v5.16.2
    environment:
      URL: /swagger-ui/spec.yml
    volumes:
      - ./swagger/spec.yml:/usr/share/nginx/html/spec.yml


  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql5:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]

volumes:
  mysql5: